### ISSUE TITLE
errors compiling on windows

### ISSUE THREAD

**Issue by seralf** [RMLio/RML-DataRetrieval#2]
HI 
while compiling from the root package RML-Mapper (I followed the instruction in the README), I get the following error on windows:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project RML-DataRetrievalHandler: Compilation failure
[ERROR] ~\RML-Mapper\RML-DataRetrieval\src\main\java\be\ugent\mmlab\rml\input\extractor\AbstractSourceExtractor.java:[30,51] error: unmappable character for encoding Cp1252
```

In order to resolve the problem, I suppose it should only a matter of adding an explicit configuration for the encoding used by some of the plugins in maven, since it seems to be using the default windows encoding.

**Comment by barthanssens** [comment]
This is actually causes inside a comment in AbstractSourceExtractor (line 30, replacing 'fancy' double quotes by straight " seems to do the trick)
